In [1]:
import pandas as pd
import numpy as np
FILE_PATH = "~/Desktop/z_hack_transaction_2009_new.csv"

In [2]:
data = pd.read_csv(filepath_or_buffer=FILE_PATH, iterator=True)

In [3]:
data1 = data.get_chunk(50)
data1

,FIRMID,FDATE,FTIME,CONTNUM,SETNUM,CONTPRICE,DIFPRICE,BAILMONEY,TRADECOMM,BUYORSAL,OPPFIRMID,OPENFLAT,OFLATLOSE,FLATLOSE
0,111112,2009-01-05,91454,10,0,2845.0,600.0,2000-0.-00,50.0,S,117224757,A,0.0,0.0
1,111112,2009-01-05,91555,10,0,2849.0,1150.0,2000-0.-00,50.0,S,117071487,A,0.0,0.0
2,111112,2009-01-05,91558,10,0,2850.0,1200.0,2000-0.-00,50.0,S,3671577,A,0.0,0.0
3,111112,2009-01-05,91555,10,0,2849.0,1150.0,2000-0.-00,50.0,S,3671577,A,0.0,0.0
4,111112,2009-01-05,91555,10,0,2850.0,1200.0,2000-0.-00,50.0,S,3671577,A,0.0,0.0
5,111112,2009-01-05,91649,10,0,2850.0,1200.0,2000-0.-00,50.0,S,119360007,A,0.0,0.0
6,111112,2009-01-05,91649,10,0,2850.0,1200.0,2000-0.-00,50.0,S,3671577,A,0.0,0.0
7,111112,2009-01-05,91649,10,0,2851.0,1250.0,2000-0.-00,50.0,S,3671577,A,0.0,0.0
8,111112,2009-01-05,91832,1,0,2852.0,130.0,2000.00,5.0,S,3671577,A,0.0,0.0
9,111112,2009-01-05,91832,10,0,2851.0,1250.0,2000-0.-00,50.0,S,3671577,A,0.0,0.0
10,111112,2009-01-05,91853,10,0,2849.0,800.0,2000-0.-00,50.0,S,3671577,A,0.0,0.0
11,111112,2009-01-05,91853,10,0,2849.0,800.0,2000-0.-00,50.0,S,3671577,A,0.0,0.0
12,111112,2009-01-05,91900,6,0,2850.0,510.0,12000.00,30.0,S,117445887,A,0.0,0.0
13,111112,2009-01-05,91905,4,0,2850.0,340.0,8000.00,20.0,S,117445887,A,0.0,0.0
14,111112,2009-01-05,92100,9,0,2852.0,1170.0,18000.00,45.0,S,3671577,A,0.0,0.0
15,111112,2009-01-05,94036,6,0,2830.0,-90.0,12000.00,30.0,S,121194567,A,0.0,0.0
16,111112,2009-01-05,94034,2,0,2830.0,-30.0,4000.00,10.0,S,1433367,A,0.0,0.0
17,111112,2009-01-05,94106,2,0,2830.0,-30.0,4000.00,10.0,S,123184737,A,0.0,0.0
18,111112,2009-01-05,94118,5,0,2837.0,750.0,10000.00,25.0,S,120051477,A,0.0,0.0
19,111112,2009-01-05,94114,5,0,2837.0,750.0,10000.00,25.0,S,117071487,A,0.0,0.0
20,111112,2009-01-05,94120,3,0,2829.0,45.0,6000.00,15.0,S,120657537,A,0.0,0.0
21,111112,2009-01-05,94121,3,0,2829.0,45.0,6000.00,15.0,S,371007,A,0.0,0.0
22,111112,2009-01-05,94126,4,0,2829.0,60.0,8000.00,20.0,S,117786357,A,0.0,0.0
23,111112,2009-01-05,94126,2,0,2829.0,30.0,4000.00,10.0,S,126430317,A,0.0,0.0
24,111112,2009-01-05,94137,8,0,2829.0,120.0,16000.00,40.0,S,123081777,A,0.0,0.0
25,111112,2009-01-05,94146,10,0,2830.0,200.0,2000-0.-00,50.0,S,117104247,A,0.0,0.0
26,111112,2009-01-05,94537,2,0,2830.0,-30.0,4000.00,10.0,S,123003387,A,0.0,0.0
27,111112,2009-01-05,94537,2,0,2830.0,-30.0,4000.00,10.0,S,128730537,A,0.0,0.0
28,111112,2009-01-05,94717,2,0,2824.0,-20.0,4000.00,10.0,S,120847077,A,0.0,0.0
29,111112,2009-01-05,104529,4,0,2800.0,-140.0,8000.00,20.0,S,7041177,A,0.0,0.0
30,111112,2009-01-05,104734,5,0,2800.0,-175.0,10000.00,25.0,S,91377,A,0.0,0.0
31,111112,2009-01-05,104818,5,0,2800.0,-175.0,10000.00,25.0,S,117259857,A,0.0,0.0
32,111112,2009-01-05,110637,7,0,2800.0,-245.0,14000.00,35.0,S,123063057,A,0.0,0.0
33,111112,2009-01-05,110743,5,0,2800.0,-175.0,10000.00,25.0,S,117071487,A,0.0,0.0
34,111112,2009-01-05,112048,27,0,2800.0,-945.0,54000.00,135.0,S,121305717,A,0.0,0.0
35,111112,2009-01-05,112626,5,0,2800.0,-175.0,10000.00,25.0,S,125252127,A,0.0,0.0
36,111112,2009-01-05,112922,5,0,2800.0,-175.0,10000.00,25.0,S,117652977,A,0.0,0.0
37,111112,2009-01-05,112939,5,0,2800.0,-175.0,10000.00,25.0,S,8267337,A,0.0,0.0
38,111112,2009-01-05,112943,12,0,2800.0,-420.0,24000.00,60.0,S,120847077,A,0.0,0.0
39,111112,2009-01-05,91358,10,0,2843.0,2400.0,2000-0.-00,0.0,S,118440387,A,0.0,0.0
40,111112,2009-01-05,91454,10,0,2845.0,1900.0,2000-0.-00,0.0,S,120744117,A,0.0,0.0
41,111112,2009-01-05,91555,10,0,2849.0,2700.0,2000-0.-00,0.0,S,120511287,A,0.0,0.0
42,111112,2009-01-05,91555,10,0,2849.0,2700.0,2000-0.-00,0.0,S,2457,A,0.0,0.0
43,111112,2009-01-05,91555,10,0,2850.0,2750.0,2000-0.-00,0.0,S,2457,A,0.0,0.0
44,111112,2009-01-05,91558,10,0,2850.0,2750.0,2000-0.-00,0.0,S,2457,A,0.0,0.0
45,111112,2009-01-05,91649,10,0,2850.0,2750.0,2000-0.-00,0.0,S,127726677,A,0.0,0.0
46,111112,2009-01-05,91649,10,0,2850.0,2750.0,2000-0.-00,0.0,S,2457,A,0.0,0.0
47,111112,2009-01-05,91649,10,0,2851.0,2800.0,2000-0.-00,0.0,S,2457,A,0.0,0.0
48,111112,2009-01-05,91832,15,0,2851.0,4200.0,30000.00,0.0,S,2457,A,0.0,0.0
49,111112,2009-01-05,91832,1,0,2852.0,285.0,2000.00,0.0,S,2457,A,0.0,0.0

In [4]:
data1 = data1.rename(columns={'FIRMID':'客户编号', 'CONTNUM':'成交数量', 'SETNUM':'交收数量'})

In [5]:
data1 = data1.rename(columns={'CONTPRICE':'成交价格', 'DIFPRICE':'订单盈亏'})

In [6]:
data1 = data1.rename(columns={'BAILMONEY':'履约担保金','TRADECOMM':'交易手续费', 'BUYORSAL':'买卖标识', 'OPPFIRMID':'对方客户编号'})
data1

,客户编号,FDATE,FTIME,成交数量,交收数量,成交价格,订单盈亏,履约担保金,交易手续费,买卖标识,对方客户编号,OPENFLAT,OFLATLOSE,FLATLOSE
0,111112,2009-01-05,91454,10,0,2845.0,600.0,2000-0.-00,50.0,S,117224757,A,0.0,0.0
1,111112,2009-01-05,91555,10,0,2849.0,1150.0,2000-0.-00,50.0,S,117071487,A,0.0,0.0
2,111112,2009-01-05,91558,10,0,2850.0,1200.0,2000-0.-00,50.0,S,3671577,A,0.0,0.0
3,111112,2009-01-05,91555,10,0,2849.0,1150.0,2000-0.-00,50.0,S,3671577,A,0.0,0.0
4,111112,2009-01-05,91555,10,0,2850.0,1200.0,2000-0.-00,50.0,S,3671577,A,0.0,0.0
5,111112,2009-01-05,91649,10,0,2850.0,1200.0,2000-0.-00,50.0,S,119360007,A,0.0,0.0
6,111112,2009-01-05,91649,10,0,2850.0,1200.0,2000-0.-00,50.0,S,3671577,A,0.0,0.0
7,111112,2009-01-05,91649,10,0,2851.0,1250.0,2000-0.-00,50.0,S,3671577,A,0.0,0.0
8,111112,2009-01-05,91832,1,0,2852.0,130.0,2000.00,5.0,S,3671577,A,0.0,0.0
9,111112,2009-01-05,91832,10,0,2851.0,1250.0,2000-0.-00,50.0,S,3671577,A,0.0,0.0
10,111112,2009-01-05,91853,10,0,2849.0,800.0,2000-0.-00,50.0,S,3671577,A,0.0,0.0
11,111112,2009-01-05,91853,10,0,2849.0,800.0,2000-0.-00,50.0,S,3671577,A,0.0,0.0
12,111112,2009-01-05,91900,6,0,2850.0,510.0,12000.00,30.0,S,117445887,A,0.0,0.0
13,111112,2009-01-05,91905,4,0,2850.0,340.0,8000.00,20.0,S,117445887,A,0.0,0.0
14,111112,2009-01-05,92100,9,0,2852.0,1170.0,18000.00,45.0,S,3671577,A,0.0,0.0
15,111112,2009-01-05,94036,6,0,2830.0,-90.0,12000.00,30.0,S,121194567,A,0.0,0.0
16,111112,2009-01-05,94034,2,0,2830.0,-30.0,4000.00,10.0,S,1433367,A,0.0,0.0
17,111112,2009-01-05,94106,2,0,2830.0,-30.0,4000.00,10.0,S,123184737,A,0.0,0.0
18,111112,2009-01-05,94118,5,0,2837.0,750.0,10000.00,25.0,S,120051477,A,0.0,0.0
19,111112,2009-01-05,94114,5,0,2837.0,750.0,10000.00,25.0,S,117071487,A,0.0,0.0
20,111112,2009-01-05,94120,3,0,2829.0,45.0,6000.00,15.0,S,120657537,A,0.0,0.0
21,111112,2009-01-05,94121,3,0,2829.0,45.0,6000.00,15.0,S,371007,A,0.0,0.0
22,111112,2009-01-05,94126,4,0,2829.0,60.0,8000.00,20.0,S,117786357,A,0.0,0.0
23,111112,2009-01-05,94126,2,0,2829.0,30.0,4000.00,10.0,S,126430317,A,0.0,0.0
24,111112,2009-01-05,94137,8,0,2829.0,120.0,16000.00,40.0,S,123081777,A,0.0,0.0
25,111112,2009-01-05,94146,10,0,2830.0,200.0,2000-0.-00,50.0,S,117104247,A,0.0,0.0
26,111112,2009-01-05,94537,2,0,2830.0,-30.0,4000.00,10.0,S,123003387,A,0.0,0.0
27,111112,2009-01-05,94537,2,0,2830.0,-30.0,4000.00,10.0,S,128730537,A,0.0,0.0
28,111112,2009-01-05,94717,2,0,2824.0,-20.0,4000.00,10.0,S,120847077,A,0.0,0.0
29,111112,2009-01-05,104529,4,0,2800.0,-140.0,8000.00,20.0,S,7041177,A,0.0,0.0
30,111112,2009-01-05,104734,5,0,2800.0,-175.0,10000.00,25.0,S,91377,A,0.0,0.0
31,111112,2009-01-05,104818,5,0,2800.0,-175.0,10000.00,25.0,S,117259857,A,0.0,0.0
32,111112,2009-01-05,110637,7,0,2800.0,-245.0,14000.00,35.0,S,123063057,A,0.0,0.0
33,111112,2009-01-05,110743,5,0,2800.0,-175.0,10000.00,25.0,S,117071487,A,0.0,0.0
34,111112,2009-01-05,112048,27,0,2800.0,-945.0,54000.00,135.0,S,121305717,A,0.0,0.0
35,111112,2009-01-05,112626,5,0,2800.0,-175.0,10000.00,25.0,S,125252127,A,0.0,0.0
36,111112,2009-01-05,112922,5,0,2800.0,-175.0,10000.00,25.0,S,117652977,A,0.0,0.0
37,111112,2009-01-05,112939,5,0,2800.0,-175.0,10000.00,25.0,S,8267337,A,0.0,0.0
38,111112,2009-01-05,112943,12,0,2800.0,-420.0,24000.00,60.0,S,120847077,A,0.0,0.0
39,111112,2009-01-05,91358,10,0,2843.0,2400.0,2000-0.-00,0.0,S,118440387,A,0.0,0.0
40,111112,2009-01-05,91454,10,0,2845.0,1900.0,2000-0.-00,0.0,S,120744117,A,0.0,0.0
41,111112,2009-01-05,91555,10,0,2849.0,2700.0,2000-0.-00,0.0,S,120511287,A,0.0,0.0
42,111112,2009-01-05,91555,10,0,2849.0,2700.0,2000-0.-00,0.0,S,2457,A,0.0,0.0
43,111112,2009-01-05,91555,10,0,2850.0,2750.0,2000-0.-00,0.0,S,2457,A,0.0,0.0
44,111112,2009-01-05,91558,10,0,2850.0,2750.0,2000-0.-00,0.0,S,2457,A,0.0,0.0
45,111112,2009-01-05,91649,10,0,2850.0,2750.0,2000-0.-00,0.0,S,127726677,A,0.0,0.0
46,111112,2009-01-05,91649,10,0,2850.0,2750.0,2000-0.-00,0.0,S,2457,A,0.0,0.0
47,111112,2009-01-05,91649,10,0,2851.0,2800.0,2000-0.-00,0.0,S,2457,A,0.0,0.0
48,111112,2009-01-05,91832,15,0,2851.0,4200.0,30000.00,0.0,S,2457,A,0.0,0.0
49,111112,2009-01-05,91832,1,0,2852.0,285.0,2000.00,0.0,S,2457,A,0.0,0.0

In [7]:
data1.columns

Index(['客户编号', 'FDATE', 'FTIME', '成交数量', '交收数量', '成交价格', '订单盈亏', '履约担保金',
       '交易手续费', '买卖标识', '对方客户编号', 'OPENFLAT', 'OFLATLOSE', 'FLATLOSE'],
      dtype='object')